global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using panggo_apk.Models;
global using panggo_apk.Presentation;
global using panggo_apk.DataContracts;
global using panggo_apk.DataContracts.Serialization;
global using panggo_apk.Services.Caching;
global using panggo_apk.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
